class SituacaoTipoEspecificacao < ActiveRecord::Base
  include IncrementableId
  include API::Filterable
  include API::Model

  self.table_name  = 'atendimentopublico.solicitacao_tipo_espec'
  self.primary_key = 'step_id'

  alias_attribute 'id',                                             'step_id'
  alias_attribute 'descricao',                                      'step_dssolcttipoespec'
  alias_attribute 'numero_dias_prazo',                              'step_nndiaprazo'
  alias_attribute 'indicador_pavimento_calcada',                    'step_icpavimentocalcada'
  alias_attribute 'indicador_pavimento_rua',                        'step_icpavimentorua'
  alias_attribute 'indicador_cobranca_material',                    'step_iccobrancamaterial'
  alias_attribute 'indicador_matricula',                            'step_icmatricula'
  alias_attribute 'indicador_parecer_encerramento',                 'step_icparecerencerramento'
  alias_attribute 'indicador_geracao_debito',                       'step_icgeracaodebito'
  alias_attribute 'indicador_geracao_credito',                      'step_icgeracaocredito'
  alias_attribute 'ultima_alteracao',                               'step_tmultimaalteracao'
  alias_attribute 'tipo_solicitacao_id',                            'sotp_id'
  alias_attribute 'unidade_id',                                     'unid_id'
  alias_attribute 'tipo_servico_id',                                'svtp_id'
  alias_attribute 'indicador_geracao_ordem_servico',                'step_icgeracaoordemservico'
  alias_attribute 'indicador_cliente',                              'step_iccliente'
  alias_attribute 'especificacao_imovel_situacao_id',               'esim_id'
  alias_attribute 'indicador_uso',                                  'step_icuso'
  alias_attribute 'indicador_ligacao_agua',                         'step_icligacaoagua'
  alias_attribute 'indicador_solicitante',                          'step_icsolicitante'
  alias_attribute 'indicador_verificacao_debito',                   'step_icverificardebito'
  alias_attribute 'tipo_debito_id',                                 'dbtp_id'
  alias_attribute 'valor_debito',                                   'step_vldebito'
  alias_attribute 'indicador_permissao_alterar_valor',              'step_icpermitealterarvalor'
  alias_attribute 'indicador_cobranca_juros',                       'step_iccobrarjuros'
  alias_attribute 'indicador_obrigatoriedade_documento_cliente',    'step_icdocumentoobrigatorio'
  alias_attribute 'indicador_gerado_encerramento_automatico',       'step_icencerramentoautomatico'
  alias_attribute 'indica_encerramento_gera_nova_especificacao',    'step_idnovora'
  alias_attribute 'indicador_tipo_especificacao_ourgencia',         'step_icurgencia'
  alias_attribute 'indicador_validacao_cliente_responsavel',        'step_icvaldocresponsavel'
  alias_attribute 'indicador_conta_registro_atendimento',           'step_icinformarcontara'
  alias_attribute 'codigo_constante_tipo_solicitacao',              'step_nncodigoconstante'
  alias_attribute 'indicador_contas_pagamentos_duplicidade',        'step_icinformarpgtoduplicidade'
  alias_attribute 'indicador_vencimento_alternativo_imóvel',        'step_icalterarvencimento'
  alias_attribute 'tipo_especificacao_disponível_loja_virtual',     'step_iclojavirtual'
  alias_attribute 'tipo_solicitacao__cancelar_debito_cobrar',       'step_iccanceladebitoacobrar'
  alias_attribute 'arquivo',                                        'step_nmarpop'
  alias_attribute 'step_arpop',                                     'step_arpop'

  belongs_to :registro_atendimento, foreign_key: :id, class_name: 'RegistroAtendimento'
end